# Generated by Django 2.2.16 on 2022-12-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221206_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ('id',), 'verbose_name': 'Соответствие жанра и произведения', 'verbose_name_plural': 'Таблица соответствия жанров и произведений'},
        ),
    ]
